### ISSUE TITLE
Redirect people here

### ISSUE THREAD

**Issue by davelab6** [googlefonts/tools#34]
https://github.com/googlefonts/tools/tree/master/encodings/GF%20Glyph%20Sets isn't findable by people who had the old link so we should add some readmes in the old  directories to redirect people

**Comment by felipesanches** [comment]
ok. I can do it

**Comment by felipesanches** [comment]
wait! What was the old link you're talking about?

**Comment by sberlow** [comment]
https://github.com/google/fonts/tree/master/tools/encodings/GF%202016%20Glyph%20Sets#latin

**Comment by felipesanches** [comment]
hmmm... I think you refer to the google/fonts repo URL, right?

**Comment by felipesanches** [comment]
ok, that's it! So we must actually send a pull request there in that other repo adding links to this one :-)

**Comment by felipesanches** [comment]
If someone's got the old link they'll still get a 404 page even if we add a encondings/README.md file on the google/fonts repo.

Maybe there could be some way to add this repo as a submodule of that one. But I think we may still endup with a slightly different URL, which then is not a solution to the issue.

I think that the core of the problem is that we shared URLs to the generic "master" branch, which is a bad practice since the master is a moving target and such URLs have no reference in time. We may have to deal with the broken URL now because of that.

On the other hand, I understand that a specific commit URL would also be bad in this specific scenario, since we probably wished users to get the latest improvements from that directory, right?

Did we share a single URL for the `encodings` dir? Or did we have URLs for several of the subdirectories as well. If it was just a single one, then the problem could be mitigated by re-adding an empty directory in there, except for a README file with directions to the new repo.

**Comment by davelab6** [comment]
I think 3 readme files in

https://github.com/google/fonts/tree/master/tools/

And

https://github.com/google/fonts/tree/master/tools/encodings

And

https://github.com/google/fonts/tree/master/tools/encodings/GF%202016%20Glyph%20Sets/

Should suffice. The direct files and further subdirectories we're rarely
linked to

**Comment by felipesanches** [comment]
great!

**Comment by felipesanches** [comment]
Closing it here because the issue is now tracked by the open pull request in the other repo.

**Comment by felipesanches** [comment]
@davelab6 The issue here can be closed since it's now tracked by the open pull request in the other repo.

**Comment by davelab6** [comment]
Thanks again
